export type { Debug, GeneratedElems, Timing, DebugFunctions, } from './debug/debug.js';
export type { DebugElems } from './debug/debug-elem-types.js';
export type { Loop } from './shape/loop.js';
export type { Curve } from './curve/curve.js';
export type { IntersectionResult } from './sweep-line/sweep-line.js';
export type { X } from './get-critical-points/x.js';
export type { SimplifyOptions } from './main/simplify-options.js';
export { enableDebugForBooleanOp } from './debug/debug.js';
export { getPathsFromStr } from './svg/get-paths-from-str.js';
export { beziersToSvgPathStr } from './svg/beziers-to-svg-path-str.js';
export { loopFromBeziers } from './shape/loop-from-beziers.js';
export { sweepLine } from './sweep-line/sweep-line.js';
export { doConvexPolygonsIntersect } from './geometry/do-convex-polygons-intersect.js';
export { getIntersections } from './get-critical-points/get-intersections.js';
export { areBoxesIntersectingDd } from './sweep-line/are-boxes-intersecting.js';
export { getLoopArea, getShapeArea, ddGetShapeArea } from './shape/get-shape-area.js';
export { getLoopCentroid, getShapeCentroid, ddGetShapeCentroid } from './shape/get-shape-centroid.js';
export { get2ndMomentOfInertia, getProdMomentOfInertia, ddGet2ndMomentOfInertia, ddGetProdMomentOfInertia } from './shape/get-2nd-moment-of-inertia.js';
export { getPrincipalAxes } from './shape/get-principal-axes.js';
export { reverseShapeOrientation } from './shape/reverse-shape-orientation.js';
export { getTotalShapeCurvature } from './shape/get-total-shape-curvature.js';
export { getWindingNumber } from './shape/get-winding-number.js';
export { getCentroidOfWeightedPoints } from './shape/get-centroid-of-weighted-points.js';
export { getShapeBounds } from './calc-paths/get-shape-bounds.js';
export { isLoopInLoop } from './calc-paths/is-loop-in-loop.js';
export { simplifyPaths } from './main/simplify-paths.js';
export { boolean } from './boolean/boolean.js';
export { mapDeep } from './utils/map-deep.js';
export { translateShape } from './shape/translate-shape.js';
export { scaleShape } from './shape/scale-shape.js';
export { rotateShape } from './shape/rotate-shape.js';
export { getShapeControlPointBox } from './shape/get-shape-control-point-box.js';


